# @ Numpy

 @ Numpy : Numerical python 
 
          - It is an array.
          - It is a core python library
          - We are using numpy to perform the complex operation
          - Ex : 3+5=8
          - Ex : 345678*678
          - Ex : 500!
          - It is a open source and freeware
           @ Open source - code is available for everyone
           @ Freeware - no cost
         - numpy is a fixed length
         
 @ Complex operations we are performing with the help of numpy :
 
  - Numpy is extensionsion to the multi - dimensional array
  - Array is a collection of homogeneous/similar kind of data

 1. Performing the operations on higher dimensional arrays ----complex operation
  - In a machine leaningeach feature as a dimension
  - Scalar : only magnitude
  - Ex - displacement
  - Vector : magnitude as well as dimension
  - Data visualization : 
  - Dimensionality reduction : PCA ,tSNE

 2. Complex matrix oprations :

    - 1D : vector
    - 2D : matrix 
    - 3D : cube
    - nD : tensors 
      
 a. Matrix multiplication : costly / complex  
  - Becoz of the vectorzation numpy perform the multiplication in a faster way.

 b. inverse 
 
 c. rank
 
 d. transpose
 
 e. eigen values and eigen vectors
 
 f. determinant

 @ Linear equation : 
 
                    a1x+b1y+c=0
                    a2x+b2y+c=0
                     
                   1. Simltaneous equation
                   2. Inversion,reduction -- matrix 
                   3. LPP : Simple method


 3. Numerical method and optimization :
    - In a mathematics we two kinds of method :

   1. Analytical method : (algorithm)
     - If we have a formulation, method, theorom or axionms to solve a particular problem then we called it as analytical method

   2. Numerical method (procedure) :
      - Approximation 
      - Ex : newton raphson

   3. Numerial integration : 

   4. Scientic computing :

   5. Vector computing :

   6. Statistical operation :
     - Statistic : it is a way of solving the problem with the help of data.


 @ Numpy is written in python and c
   - For using the numpy we need to import it 

 @ Syntax : import numpy as np
 
 - impoRt ---- keyword
 - numpy ---- library name
 - np---- alias 

 Q Why we are using alias ?
 - It will increase the readability

 @ Installing numpy : pip install numpy

 1. Creating numpy arrays :

    1. np.array() : We are creating the numpy array manually with the help of np,array()
    2. It will always takes list as a argument
    - syntax : ideatifier/ variable = np.array([e1,e2-----])
    - Mumpy is a fixed size

    - ex : array1=np.array([23,34,56,89,99]) ------- vector--- 1D
 
    - numer of subscript operators will decide th ,[]dimension of the numpy array
    - [] 1D
    -  [[]] 2D
    - [[[]]] 3D

 - ndim : will gives the dimension of the numpy array
 - syntax : array_name.ndim

 - ex :
        array([[1, 2, 3, 4],
        [5, 6, 7, 8]])---matrix--2D(rows and columns)

 - ex :
        array([[[1, 2],
        [3, 4]],

         [[5, 6],
        [7, 8]]])----cube--3D(length,height,width)


In [1]:
import numpy as np

In [2]:
array1=np.array([23,34,56,89,99])

In [11]:
array1

array([23, 34, 56, 89, 99])

In [12]:
array1.ndim

1

In [5]:
array2=np.array([[1,2,3,4],[5,6,7,8]])
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
array2.ndim

2

In [7]:
array3=np.array([[[1,2],[3,4],[5,6],[7,8]]])
array3

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [8]:
array3.ndim

3

 2. Creating numpy array using arrange() :
    - We are crating the numpy array by specifying the values in the arguments
    - np.arange(start,end,step_size)
    - By default it is starting from 0
    - array4=np.arange(10)
    - array5=np.arange(10,30)
    - By default step size is 1
    - array6=np.arange(10,20,3)

In [11]:
import numpy as np

In [12]:
array4=np.arange(10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array5=np.arange(10,30)
array5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [14]:
array6=np.arange(10,20,3)
array6

array([10, 13, 16, 19])

In [15]:
a=[[1,2],[3,4]]
b=[[3,4],[5,6]]
c=[[0,0],[0,0]]
for i in range(len(a)):
    for j in range(len(b)): 
        c[i][j]=a[i][j]+b[i][j]
print(c)        

[[4, 6], [8, 10]]


In [16]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[3,4],[5,6]])

In [17]:
a1+a2

array([[ 4,  6],
       [ 8, 10]])

In [18]:
a=[[1,2],[3,4]]
b=[[3,4],[5,6]]
c=[[0,0],[0,0]]
for i in range(len(a)):
    for j in range(len(b)):
        for k in range(len(b)):
            c[i][j]+=a[i][k]*b[k][j]
print(c)

[[13, 16], [29, 36]]


In [19]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[3,4],[5,6]])


In [20]:
a1*a2

array([[ 3,  8],
       [15, 24]])

In [21]:
a1.dot(a2)

array([[13, 16],
       [29, 36]])

 @ Difference between list and numpy array :

 @ List :
 
        - Collection of heterogeneous items
        - List is a variable size
        - List is not memory efficient because for one item it is creating two blocks of memory
        - So we required every time one block extra memeory for each item
        - Whenever we are storing the list in the memory ,the item will be stored whereever the space is available in the memory.
        - Matrix operations are slow in list
        - To perform the matrix operation in list we have to iterate it becoz of that time and space both are getting increase


 @ Numpy :
 
         - Collection of similar kind of data items
         - It is of fixed size
         - Numpy array will be stored inside the memory in a consecutive manner
         - So it is memory efficient
         - Numpy is more closer to the hardware 
         - Numpy is faster than list becoz it will follows the spatial or temporal aspect of cache
         - It is possible because of consecutive storing behaviour of numpy

 @ Aspects of cache :
 
   - Spatial : Instead of loading one block load the consecutive block also
   - temporal aspect : Instead of loading consecutive block load the entire array
   - Matrix operations are faster in numpy because of vectorization.
   - In case of numpy array we don't need to iterate the matrix so it efficient
   - Numpy will provide matrix multiplication in two ways

    1. Element wise multiplication
    2. Dot product

 @ Scalar : Magnetude
 
 @ Vector : Magnetude as well as direction

 3. Creating numpy array using np.zeros() :
 - It will create the numpy array with all elements zeros
 - If we are giving the order of a matrix as a argument then we have to give it in the form of tuple
 - arr1=np.zeros(5)
 - arr2=np.zeros((3,3))
 - Zero matrix we called it as initialization matrix

In [22]:
arr1=np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [23]:
arr2=np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

 4. Creating numpy array using np.ones() :
   - It will create numpy array with all elemnets one
   - If we are giving the order of a matrix as a argument then we have to give it in the form of tuple
   - Ex : arr3=np.ones(5)
   - arr4=np.ones((3,3))

In [24]:
arr3=np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [25]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

 5. Creating numpy array using np.eye() :

   - It will make all the principal diagonal elements 1 
   - arr7=np.eye(2,3)
   - arr5=np.eye(3,3)
   - arr6=np.eye(4)

In [1]:
import numpy as np

In [2]:
arr5=np.eye(3,3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
arr6=np.eye(4)
arr6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
arr7=np.eye(2,3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.]])

 6. Creating numpy array using np.diag() :
   - It will create the diagonal matrix
   - It will always takes the argument in the form of list
   - d1=np.diag([1,2,3])
   - For creating the matrix of the combinations of zeros and ones ,we have to create it manually

In [5]:
d1=np.diag([1,2,3])
d1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [6]:
d2=2*np.ones((3,3))
d2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [7]:
a=np.diag([1,2,3,4,5])
b=np.diag([3,4,5,6,7])
a*b

array([[ 3,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0,  0, 24,  0],
       [ 0,  0,  0,  0, 35]])

In [8]:
a.dot(b)

array([[ 3,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0,  0, 24,  0],
       [ 0,  0,  0,  0, 35]])

 7. Creating numpy array using np.linspace() :
   - It is used to create 1D numpy array (vector)
   - It will create the values as per the limit
   - And if we are not specifying the equidistant points by default it will take 50 points  
   - Syntax : np.linspace(start,end,no_equi_points)
   - For samplings (when we don't have the proper sampling points)

In [9]:
x=np.linspace(10,20,10)
x

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
y=np.linspace(0,1)
y

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

 8. np.random.rand() :
 - It will create the random values array as per the limit according to the uniform distribution
 - Uniform distribution : each value as qrally likely chance of getting selected
 - It will take all the value less than or equals to zero becoz probability should not be greater than 1
 - r1=np.random.rand(3,3)

In [ ]:
import numpy as np

In [11]:
r=np.random.rand(5)
r

array([0.17814247, 0.4174395 , 0.77239142, 0.04641605, 0.95904727])

In [12]:
r1=np.random.rand(3,3)
r1

array([[0.43421098, 0.92510224, 0.03408966],
       [0.06088275, 0.24573545, 0.25504379],
       [0.39210036, 0.42792691, 0.69639352]])

 9. np.random.randn() :
  - It will also gives the random values as per the standard normal variate(standard normal distribution)
  - r2=np.random.randn(5)

In [13]:
r2=np.random.randn(5)
r2

array([-2.07221991, -1.76845711,  0.01984189, -0.89087509, -0.31774945])

 10. np.randon.randint() :
 - It will genrate the numpy array with any random values as per the range
 - r3=np.random.randint(10,20,(3,3))
 - np.random.randint(start,end,no_of_elememts)

In [14]:
r3=np.random.randint(10,20,5)
r3

array([16, 16, 10, 15, 12], dtype=int32)

In [15]:
r4=np.random.randint(10,20,(3,3))
r4

array([[10, 18, 19],
       [15, 19, 11],
       [17, 19, 12]], dtype=int32)

 11. copy() :
 - It will copy the elements from one array to another array

In [ ]:
import numpy as np

In [16]:
a1=np.array([1,2,3,4,5])
a2=a1.copy()
a2

array([1, 2, 3, 4, 5])

 @ Numpy class are having the attribute :
 1. ndim : It will gives the dimension of the numpy array
 2. shape :It will gives the order of the array
 3. size : No of element present in the array
 4. iteamsize : How much memory each element of the array is occupying
 5. dtype : It will gives the data type of the array
 6. astype() : It is use for typecasting

In [20]:
z=np.array([1,2,3,4,5])

In [22]:
z.ndim

1

In [21]:
z.shape

(5,)

In [24]:
z1=np.array([[1,2,3,4],[3,4,5,6]])
z1.shape

(2, 4)

In [25]:
z.size

5

In [26]:
z1.size

8

In [27]:
z.itemsize

8

In [29]:
z1.itemsize

8

In [30]:
z.dtype

dtype('int64')

In [31]:
z1.dtype

dtype('int64')

In [34]:
z=z.astype('float')
z.dtype

dtype('float64')

In [35]:
z.itemsize

8

 1.Matrix operations:
 
  1. Addition
  2. Subtraction
  3. Mutiplication : a. Elementwise  b. Dotproduct
  4. Transpose
  5. Determinant
  6. Inverse
  7. Rank

 1. Trace : Sum of the diagonal elements of the array
 - Syntax:np.trace(array_name)


In [19]:
list1=[[1,2],[4,5]]
trace=0
for i in range(len(list1)):
    for j in range(len(list1)):
        if i==j:
            trace+=list1[i][j]
print(trace)

6


 2.Transpose of a matrix:
 - Converting the rows of matrix into columns and columns into rows
 - syntax: array_name.T

In [ ]:
import numpy as np

In [37]:
p=np.array([[1,2],[3,4]])
np.trace(p)

np.int64(5)

In [38]:
p

array([[1, 2],
       [3, 4]])

In [39]:
p=p.T
p

array([[1, 3],
       [2, 4]])

In [40]:
p

array([[1, 3],
       [2, 4]])

 3.Inverse of matrix:
 - It will give the inverse of the matrix
 - np.linalg.inv(p)


In [ ]:
import numpy as np 

In [41]:
np.linalg.inv(p)

array([[-2. ,  1.5],
       [ 1. , -0.5]])

 4. Determinant :
   - np.linalg.det(a)

In [43]:
a=np.array([[1,2],[3,4]])
np.linalg.matrix_rank(a)

np.int64(2)

In [44]:
a=np.array([[1,2,3,4,5],[3,4,5,6,7],[4,5,6,7,8]])
np.linalg.matrix_rank(a)

np.int64(2)

 5. Rank :
  - It will gives the rank of matrix 
  - On of linearly independent rows and columns in the matrix 
  - np.linalg.matrix_rank(a)

In [45]:
a = np.array ([1,2,3,4,5])
a+1

array([2, 3, 4, 5, 6])

In [46]:
a-1

array([0, 1, 2, 3, 4])

In [47]:
a*2

array([ 2,  4,  6,  8, 10])

In [49]:
a**2

array([ 1,  4,  9, 16, 25])

 2. Arithmatic operations on numpy :


               1.Addition(+)
               2.Subtraction(-)
               3.Mutiplication(*)
               4.Division(/)
               5.Floor Division(//)
               6.Power(**)
               7.Modulus(%)
    
 -  All the arithmetic operations are done elementwise

In [54]:
import numpy as np

In [55]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [56]:
a+b

array([ 6,  8, 10, 12])

In [57]:
a-b

array([-4, -4, -4, -4])

In [58]:
a*b

array([ 5, 12, 21, 32])

In [59]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [51]:
a//b

C:\Users\Komal prakash mali\AppData\Local\Temp\ipykernel_15232\2860853455.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  a//b


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [50]:
a%b

C:\Users\Komal prakash mali\AppData\Local\Temp\ipykernel_15232\1820107994.py:1: RuntimeWarning: divide by zero encountered in remainder
  a%b


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [62]:
x=np.array([3,4,5,6,7])
x=x+1
x

array([4, 5, 6, 7, 8])

In [63]:
x-1

array([3, 4, 5, 6, 7])

In [64]:
x*2

array([ 8, 10, 12, 14, 16])

In [67]:
x**2

array([16, 25, 36, 49, 64])

 3. Scalar operation  on numpy array :
   - We are performing the operation  with the help of scalar

In [72]:
a=np.ones((3,3))+1
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

 4. Relational Operations :
 - It is used to find the relation between the elements of the numpy array
 - >,<,==,!=,>=,<=---It will compare elementwise
 - np.array_equal(p1,p2)---It will compare arraywise


In [73]:
a1=np.array([4,5,6,7,8])
a2=np.array([2,3,4,5,8])

In [74]:
a1>a2

array([ True,  True,  True,  True, False])

In [75]:
a1<a2

array([False, False, False, False, False])

In [76]:
a1==a2

array([False, False, False, False,  True])

In [77]:
a1!=a2

array([ True,  True,  True,  True, False])

In [79]:
p1=np.array([1,2,45,67])
p2=np.array([1,2,45,98])
p3=np.array([1,2,45,67])
np.array_equal(p1,p2)

False

In [80]:
np.array_equal(p1,p3)

True

 5. Logical operations on numpy :

 - all() : - It will return true value when all the elements in the array are true 
           - Every non zero is considered as true otherwise false
 - any() : - It will return true if atleast one value true otherwise false
 - logical_or
 - logical_and

In [81]:
s=np.array([1,0,3,4,5])
np.all(s)

np.False_

In [82]:
s=np.array([1,0,3,4,5])
np.any(s)

np.True_

In [83]:
a=np.array([2,0,0,1,3])
b=np.array([4,5,0,0,56])
np.logical_or(a,b)

array([ True,  True, False,  True,  True])

In [84]:
a=np.array([2,0,0,1,3])
b=np.array([4,5,0,0,56])
np.logical_and(a,b)

array([ True, False, False, False,  True])

 6. Transcendental Operations :
   - When we have a log,exp(e),trigonometry------
   - np.log() : it will give the log of each value present in numpy array
   - np.exp() : it is giving the exponential value of each element of numpy array
   - np.sin()
   - np.cos()

In [85]:
a=np.array([2,3,4,5,6])
np.log(a)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947])

In [86]:
np.exp(a)

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ,
       403.42879349])

In [87]:
a=np.array([3,4,5,6,30])
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 , -0.98803162])

In [88]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.15425145])

 7. Sorting :
    - np.sort() - it will sort in ascending order
                  - it is not in-place sort
    - numpy_array.sort() - it will perform inplace sorting
    - np.argsort() - it will perform the sorting on the basis of index of the numpy array

 @ Row wise sorting : axis =1
 
 @ ColumN wise sorting : axis 0
      

In [89]:
a=([3,4,-5,-67,2,1])
b=np.sort(a)
a

[3, 4, -5, -67, 2, 1]

In [90]:
b

array([-67,  -5,   1,   2,   3,   4])

In [91]:
c=np.argsort(a)
c

array([3, 2, 5, 4, 0, 1])

In [92]:
d=np.array([5,0,-1,-3,7,-24])
d.sort()
d

array([-24,  -3,  -1,   0,   5,   7])

In [ ]:
import numpy as np

In [93]:
mat1=np.array([[1,2,-3],[4,-5,6],[-7,8,9]])
mat2=np.sort(mat1)
mat2

array([[-3,  1,  2],
       [-5,  4,  6],
       [-7,  8,  9]])

In [94]:
mat3=np.argsort(mat1)
mat3

array([[2, 0, 1],
       [1, 0, 2],
       [0, 1, 2]])

In [95]:
mat1.sort()
mat1

array([[-3,  1,  2],
       [-5,  4,  6],
       [-7,  8,  9]])

In [96]:
m=np.array([[1,2,-3],[4,-5,6],[-7,8,9]])
m

array([[ 1,  2, -3],
       [ 4, -5,  6],
       [-7,  8,  9]])

In [98]:
m=np.sort(m,axis=0)
m

array([[-7, -5, -3],
       [ 1,  2,  6],
       [ 4,  8,  9]])

In [97]:
o=np.argsort(m,axis=0)
o

array([[2, 1, 0],
       [0, 0, 1],
       [1, 2, 2]])

In [99]:
m.sort(axis=0)
m

array([[-7, -5, -3],
       [ 1,  2,  6],
       [ 4,  8,  9]])

In [100]:
a=np.array([34,-11,-22,17,79,90,-100])
rev_sorted=np.sort(a)[::-1]
rev_sorted

array([  90,   79,   34,   17,  -11,  -22, -100])

 8. Aggregation Operations :
 - sum() :
 - max():
 - min() :
 - argmax() :
 - argmin() :

In [101]:
ab=np.array([3,4,5,6,7,8])

In [102]:
np.sum(ab)

np.int64(33)

In [103]:
np.max(ab)

np.int64(8)

In [104]:
np.min(ab)

np.int64(3)

In [105]:
np.argmax(ab)

np.int64(5)

In [107]:
np.argmin(ab)

np.int64(0)

 9. searching in numpy array :
    1. np.where (condition): it will retrun the index of the elements where the condition is true
    2. np.nonzero() : it will return the index of the nonzero elements in the array
    - syntax : np.nonzero(array_name)
    3. np extract() : it will return the element based on the conditions
    - syntax:np.extract(condition,array_name)

In [3]:
import numpy as np

In [9]:
a=np.array([2,3,4,5])
b=np.array([1,2,3,4])
c=np.array([2,3,4,5])

In [10]:
np.array_equal(a,b)

False

In [11]:
np.array_equal(a,c)

True

In [4]:
a=np.array([3,4,5,1,7])
np.where(a>2)

(array([0, 1, 2, 4]),)

In [5]:
np.where(a==2)

(array([], dtype=int64),)

In [6]:
np.where(a==3)

(array([0]),)

In [12]:
np.where(a==0)

(array([], dtype=int64),)

In [13]:
b=np.array([2,3,4,0,5,6,0,0])
np.nonzero(b)

(array([0, 1, 2, 4, 5]),)

In [14]:
c=np.array([4,5,6,11,19,20])
np.extract(c>5,c)

array([ 6, 11, 19, 20])

 10. Numpy is a fixed length :
 
 @ np.append() :
 
               - It is used to add the element in the numpy array 
               - It will not make changes directly in exixting array,we have to create a new array to see the changes
               - It is taking extra array for append
               - Syntax : np.append(array,element)

 @ np.insert() : 
 
               - It will insert the element into numpay array at the particular position
               - But to see the changes we have create another numpy array
               - Syntax: np.insert(array_name,index,item)

In [18]:
p=np.array([3,4,5,6,7])
np.append(p,45)


array([ 3,  4,  5,  6,  7, 45])

In [19]:
p

array([3, 4, 5, 6, 7])

In [37]:
q=np.array([3,4,5,6,7,8,9])

In [36]:
q

array([ 3,  4,  5,  6, 10,  7,  8,  9])

 np.concatenate():
 
     - It is used to concatenate the numpy array to another numpy array
     - It will create a numpy array
     - Syntax : np.concatenate(array_name,([i1,i2---]))

In [27]:
array3=np.array([45,67,89,90,100])
array4=np.concatenate((array3,np.array([1,2,3,4])))
array4

array([ 45,  67,  89,  90, 100,   1,   2,   3,   4])

 @ Reshaping : 
  
     - It convert the one numpy array into another dimensions

 @ Syntax :
 
      1.array_name=np.array([]).reshape(x_dim,y_dim)
      2.array_name.reshape()

 @ Number of elements before reshaping and after reshaping must be equal
 
 @ If only one row present in a matrix:row vector:(1*n)
 
 @ If only one column present in a matrix:column vector:(n*1)
 
 @ 12 :  3*4,4*3,6*2,2*6,(2*2*3)

In [28]:
a1=np.array([0,0,0,0,0,0,0,0,0,0,1,0])
a1.shape

(12,)

In [29]:
a1.reshape(12,1)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [30]:
a1.reshape(3,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0]])

In [31]:
a1.reshape(4,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

In [32]:
a1.reshape(6,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0]])

In [33]:
a1.reshape(2,6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [34]:
a1.reshape(2,2,3)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 0]]])

In [ ]:
import numpy as np

 @ Accessing the elements of numpy arrays :  

In [38]:
a=np.array([1,2,3,4,5,6,7])
a[2]

np.int64(3)

In [39]:
b=np.array([[1,2],[4,5]])
b[1][0]

np.int64(4)

In [65]:
c=np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
c[2:6]

array([2, 3, 4, 5])

In [68]:
c[5:]=10
c

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [69]:
a1=np.arange(10)
a2=np.arange(5)

In [71]:
a1[5:]=a2[::-1]
a1

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [73]:
b1=np.array([2,3,4,5])
b2=np.array([1,2,3,4])
b3=np.array([2,3,4,5])
d=((b1<=b2) & (b1<=b3)).all()
d

np.False_

 @ Statistical operations on numpy array :
    
 @ Statistics : Way of solving a problem with the help of data
 1. descriptive statistics :
    - Describing the data
    - We have different techniques and measures in descriptive stats to describe the data
    - We want to explore the data

 @ Statistics measures:

 @ First moment business decision (measures of central tendencies)

 1.Mean :
 
        - Average of the data pointer
        - Mean=(sum of all observations)/total number of observation
        - Base pizza : Hyderabd
          s1:110
          s2:120
          s3:100
          s4:110
          s5:100
        - Avg(pizza_price)=108
        - Mean is influenced by outliers
        - Outliers means a datapoint which is not in a range (out of context value)
        - Whenever we have outliers in the dataset better not to use mean
        - Syntax : np.mean(array_name)

 2.Median : Average
 
         s1:110
         s2:120
         s3:100
         s4:110
         s5:900----avg(pizza_price)=268--mean---outliers:
       - Median(pizza_price)=120
       - Whenever we have outliers in datset we have to use median
       - Median is not influenced by outliers
       
 @ Method to find median :
 
       - Sort the data points in ascending order
       - If there is odd no of datapoints:median=middle number 
       - If there is even number of datapoints then
       - Median=(middle_element+(middle_element+1))//2
       - Syntax : np.median(array_name)

 
 3.Mode--(scipy) : There are two type of data in a statistics
 
                1. Numrical data or continuous :
                
                                                - It will contains the numerical value
                                                - Numrical data again classify into two data : 
                                                  a. Continuous data : 
                                                                     - It is having continuous real value
                                                                     - Ex : weight,height etc
                                                  b. Discete data :
                                                                  - It will not contain fractional value
                                                                  - Ex : count of students etc
 @ mean and median will works on numerical data only

                 2. Catagorial data : 
                                     - It will specify the ctagory
                                     - We cannot find out the mean and median for catagorical data
                                     
 3.Mode :
  
        - It will work on the categorical data
        - Mode means maximum occurrence of the data pointers
        - There can be multiple modes in the dataset we called it as multimodal dataset 
        - If we unwanted to select any one or two its completely depens upon problem statement
        
                                     
 @ Second moment business decision : (measures of the dispersion) 
   
   -  Dispersion means how the data point are varying

 1.Range :
 
         - Max of array and min of array
         - Max(array)
         - Min(Array)
      
 2.Standard Deviation : 
           
          -  It is a square root of variance
          - np.std(array_name)
                     
 3.Variance :
 
            - How for each data point from the average
            - syntax:np.var(Array_name)

 @ Cumsum :
 
          - [1,2,3,4,5]:[1,3,6,,10,]
          - np.cumsum(array_name)

 @ Percentile :[12-----------n]

             - 50 percentile:how many data points are there which is less that 50% percent value
             - 90 percentile 
             - np.percentile(array_name,value)

 2.Inferential Statistics :
 -  We are making some concusion based on the sample and infering about the population 

 @ Corelation : Relationship between two feature
 
       rho :  1------- strong relation
             -1-------- weak relation
              0 -------- no relation 
              syntax : corrcoef(a1,a1)
 

In [40]:
import numpy as np

In [41]:
a=np.array([3,4,5,6,7,8])
for i in a:
    print(i)

3
4
5
6
7
8


In [62]:
b=np.random.randint(10,30,(4,5)).reshape(5,4)
b

array([[11, 16, 27, 21],
       [20, 29, 15, 18],
       [13, 12, 20, 14],
       [16, 24, 17, 20],
       [13, 17, 15, 11]], dtype=int32)

In [64]:
for i in range(len(b)):
    for j in range(len(b[0])):
        print(b[i][j])

11
16
27
21
20
29
15
18
13
12
20
14
16
24
17
20
13
17
15
11


In [63]:
b

array([[11, 16, 27, 21],
       [20, 29, 15, 18],
       [13, 12, 20, 14],
       [16, 24, 17, 20],
       [13, 17, 15, 11]], dtype=int32)

In [6]:
b[1,3]

np.int32(24)

In [7]:
b

array([[24, 25, 25, 17],
       [10, 22, 29, 24],
       [14, 11, 25, 27],
       [20, 24, 25, 24],
       [26, 18, 14, 19]], dtype=int32)

In [8]:
b>15

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [58]:
mask=b>15
mask

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [59]:
a[a>15]

array([], dtype=int64)

In [10]:
f11=(b>15) & (b%2==0)
f11

array([[ True, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False],
       [ True,  True, False,  True],
       [ True,  True, False, False]])

 @ Broadcasting :

                   - Its ability to exapand the array to perform the operations with the larger array
                   - Broadcasting is a process to perform the operation of small matrices and large matrix
                   - With the help of this concept different size matrix operation can perform

In [11]:
a=np.ones((3,3))+4                 
a

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [12]:
a1=np.array([[1,2],[3,4]])
a2=np.array([1,2])
a2

array([1, 2])

In [13]:
a1

array([[1, 2],
       [3, 4]])

In [14]:
a1+a2

array([[2, 4],
       [4, 6]])

In [19]:
aa1=np.arange(9).reshape(3,3)
aa2=np.arange(3).reshape(3,1)

In [18]:
aa1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
aa2

array([[0],
       [1],
       [2]])

In [21]:
aa1+aa2

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [55]:
aa4=np.arange(10).reshape(2,5)
aa5=np.arange(9).reshape(3,3)
aa4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
aa5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
aa8=np.arange(18).reshape(3,6)
aa9=np.arange(3).reshape(3,1)
aa8+aa9

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18, 19]])

 Q We have 3D numpy array with random we need to add there array using loop 

 RMO : Row major order
 
     - np.reshape(array_name,dimension,'c')
     - C :PL will follows the Row major order

 CMO : 
 
     - np.reshape(array_name,dimension,'F')
     - FORTRAN PL will follows CMO

 @ Concatenate two matrixces :
 - np.concatenate ([])
 - np.hstack ([]): it will concatenate two matrix 
 - Horizontally
 - np.vstack ([]): it will concatenate two matrix 
 - Vertically

In [1]:
import numpy as np

In [3]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.reshape(a,(1,9),'c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [5]:
np.reshape(a,(1,9),'F')

array([[0, 3, 6, 1, 4, 7, 2, 5, 8]])

In [6]:
a1=np.array ([[1,2],[3,4]])
a2=np.array ([[5,6],[7,8]])
np.concatenate([a1,a2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
np.hstack([a1,a2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [8]:
np.vstack([a1,a2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

 @ Copy and views ---------- Importance Q for interview
 
 @ copy () :
 
           - When we use the copy (),it will create duplicate array with different buffer. 
           - The changes made in copied array will not affect the original array and vice versa.
           - When we are using copy we required extra memory buffer so it is not memory effieciecient.
           - When we are using copy () we have to stored the data as well as meta data.

 @ view () :
 
           - Whenvwe use view () t will not create the copy it will create view.
           - Both original array and view are at the same place.
           - so we dont required extra buffer to stored data.
           - But we required to stored the metadata to differentiate two array.
           - So view () is memory efficient. 
           - By using the view () numpy will do the memory optimization.
           - To check the both array at same space.
           - np.shares_memory(arr1,arr2)

In [12]:
aa1=np.array([1,2,3,4,5])
aa2=aa1.copy()
aa2[1]=1000
print(aa1)
print(aa2)


[1 2 3 4 5]
[   1 1000    3    4    5]


In [14]:
aa1=np.array([5,6,7,8,9])
aa2=aa1.view()
aa2[0]=2000
print(aa1)
print(aa2)


[2000    6    7    8    9]
[2000    6    7    8    9]


In [17]:
 np.shares_memory(aa1,aa2)

True

 @ Flattening :
 
              - Converting multidimensional array into single dimension.
              - array_name.flatten()----copy()-----it is not memory efficient

 @ Ravel () :
 
            - Converting multidimensional array into single dimension.
            - array_name.ravel()------ view

 @ Reshaping is also copying so it is not memory efficient operation.

In [47]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
c=b.flatten()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
d=b.ravel()
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
c[0]=200
c

array([200,   1,   2,   3,   4,   5,   6,   7,   8])

In [53]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
e=np.zeros((3,2))
f=e.T.reshape(3,2)
f[0]=500

In [43]:
e

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [44]:
f

array([[500., 500.],
       [  0.,   0.],
       [  0.,   0.]])

In [22]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
p=s[::2]
p

array([0, 2, 4, 6, 8])

In [24]:
np.shares_memory(s,p)

True

In [26]:
Q=s[::2].copy()
Q

array([0, 2, 4, 6, 8])

In [28]:
np.shares_memory(s,Q)

False